# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: AKS-agentpool

steps:
# - task: CmdLine@2
#   inputs:
#     script: 'kubectl apply -f azure-vote-all-in-one-redis.yaml'

- task: CmdLine@2
  inputs:
    script: 'ps aux | grep myagent'


- task: AzureCLI@2
  inputs:
    azureSubscription: 'AKS_SP3'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # az login --identity
      # kubectl get nodes
      kubectl apply -f azure-vote-all-in-one-redis.yaml



# - task: Kubernetes@1
#   inputs:
#     connectionType: 'Azure Resource Manager'
#     azureSubscriptionEndpoint: 'AKS_SP2'
#     azureResourceGroup: 'az-k8s-6460-rg'
#     kubernetesCluster: 'aks-az-k8s-6460'
#     command: 'apply'
#     arguments: '-f azure-vote-all-in-one-redis.yaml'
#     secretType: 'dockerRegistry'
#     containerRegistryType: 'Azure Container Registry'
#     checkLatest: true