# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: AKS-agentpool

steps:
# - task: CmdLine@2
#   inputs:
#     script: 'kubectl apply -f azure-vote-all-in-one-redis.yaml'

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'AKS_Service_Account'
    command: 'apply'
    arguments: '-f azure-vote-all-in-one-redis.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'