# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: AKS-agentpool

steps:
# - task: CmdLine@2
#   inputs:
#     script: 'kubectl apply -f azure-vote-all-in-one-redis.yaml'

- task: CmdLine@2
  inputs:
    script: 'ps aux | grep myagent'

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'AKS_SC_MI'
    azureResourceGroup: 'az-k8s-6460-rg'
    kubernetesCluster: 'aks-az-k8s-6460'
    command: 'apply'
    arguments: '-f azure-vote-all-in-one-redis.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'